import React from 'react';

const About = () => {
  return (
    <div>
      <h2>Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h2>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat! Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h3>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat! Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h3>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat! Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h3>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat!Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h3>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat!Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h3>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat! Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h3>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat! Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. Welcome to the our company. </h3>
      <p>This was all about our company.</p>
      <h3>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit velit officia quia perspiciatis fugiat non a rerum incidunt libero, quae ipsum numquam praesentium veniam tenetur ipsam adipisci dolorum aperiam quaerat!</h3>
    </div>
  );
};

export default About;